### ISSUE TITLE
forceInclude not working

### ISSUE THREAD

**Issue by Webjin** [claudio-silva/grunt-angular-builder#17]
First of all: I really like the build tool! Can't believe you only have 37 stars at the time of this writing. Great documentation too!

I can't get forceInclude to work, this is how my configuration looks. I'm using 1.0.0beta3
```javascript
		'angular-builder': {
			options: {
				mainModule: 'app.core',
				externalModules: [
				],
				debugBuild: {
					rebaseDebugUrls: [
						{ match: /^public_html\//, replaceWith: '/' }
					]
				},
				forceInclude: [
					basePath + 'bower_components/angular/angular.min.js'
				]
			},
			forceInclude: [
				basePath + 'bower_components/angular/angular.min.js'
			],
			dist: {
				forceInclude: [
					basePath + 'bower_components/angular/angular.min.js'
				],
				src: [
					basePath + 'app/*.js',
					basePath + 'app/**/*.js',
				],
				dest: basePath + 'dist/app.core.js'
			}
		}
...

**Comment by claudio-silva** [comment]
Hi @Webjin,
Yes, I agree with you: it's a shame this project has so little stars! :-)
Truth be said, I didn't do anything to promote it anywhere, but still I would like it to be more popular, as everyone at our company believe it to be a great solution for building angular.js based projects.
But now, with Angular 2.0 on the horizon, it will eventually become obsolete, as Angular is going to adopt an ES6 module loader. But with this tool, there would be no need for such a module loader and I believe this solution to be more practical and requiring you to write less glue code.
For anyone using Angular 1.x, this is the best solution IMHO.

Now, regarding your problem:
I see you have too many `forceInclude` properties lying around. I guess you were desperate and tried to put it everywhere ;-)
The correct place to put it is near a `src` property, all other locations are invalid.
`forceInclude` is of type `string` so, perhaps if you dropped the array and just leave the string there, it might work...
A word of caution: I see what you're trying to do here; you want to include the angular framework itself in the build output file. It is not advisable to do it this way. You may load Angular via a separate script tag on your html file, or you may use the `grunt-contrib-concat` plugin to prepend the `angular.min.js` file to the build output.
Use `forceInclude` when you have non-angular javascript scripts that are part of your application (any application code not integrated into an angular module); do not use if for third-party libraries.
We use 'concat' on our projects and it works quite well.

**Comment by claudio-silva** [comment]
I've just re-read the documentation and found out `forceInclude` can be an array of strings. My mistake, sorry about that.
So, I guess `angular.min.js` is not being included because it contains angular module declarations. As those modules are not specifically (although they are implicitly) required by your application, the "tree shaking" algorithm discards the "dead" code.
As I explained before, you should use `grunt-contrib-concat` for this. Save `forceInclude` for non-angular application code.
I hope this helps.

**Comment by claudio-silva** [comment]
@Webjin, as I've got no response from you, I assume you've managed to solve your issue, so I'm closing this.
