### ISSUE TITLE
Warning: Maximum call stack size exceeded Use --force to continue.

### ISSUE THREAD

**Issue by acnalesso** [claudio-silva/grunt-angular-builder#18]
Hi there,

I am trying to build my app into /dist dir but I keep getting this error.
This is my config in Grunfile.js

```json
'angular-builder': {
      options: {
        mainModule: 'preregApp',
        externalModules: ['ngSanitize', 'ngResource']
      },

      app: {
        src: 'app/js/**/*.js',
        dest: 'dist/app.js'
      }
    },
```

This is what my app.js looks like:
```js
'use strict';

/* App Module */

var preregApp = angular.module('preregApp', [
   'ngSanitize',
   'myServices',
   'myControllers',
   'myCommonDirectives',
   'myDirectives'
]);
```

<strong>myServices</strong> relies on ngResource.

Would you be able to help me figuring this out?

Many thanks

**Comment by acnalesso** [comment]
Hi there!

Found out what it was.

In the <b>myServices</b> module I was passing <b>preregApp</b> as a dependency therefore it was in an endless loop and per the error message.

Great, thanks for this awesome plugin.

Have fun,
ABC

**Comment by claudio-silva** [comment]
You're welcome. :-)
