### ISSUE TITLE
Build multiple modules from the same source

### ISSUE THREAD

**Issue by sokolandia** [claudio-silva/grunt-angular-builder#19]
I have two modules that may use the same services:
```javascript
// File: modules/app1.js
var app = "app1";
angular.module(app, []);
```
and
```javascript
// File: modules/app2.js
var app = "app2";
angular.module(app, []);
```
with a factory
```javascript
// File: providers/commonFactory.js
angular.module(app).factory("commonFactory", function(){ return {}; });
```
Then I concatenate both `modules/app1.js` and `modules/app2.js` with a factory `providers/commonFactory.js` and the `app` reference in a factory file gets resolved with an appropriate module name:
```javascript
// File: build/app1.js
var app = "app1";
angular.module(app, []);
angular.module(app).factory("commonFactory", function(){ return {}; });
```
and
```javascript
// File: build/app2.js
var app = "app2";
angular.module(app, []);
angular.module(app).factory("commonFactory", function(){ return {}; });
```
The problem is that I have to manually specify which services have to be concatenated to which modules if I want to avoid having redundant code so I decided to try out your tool. Also I don't know in advance which services are going to be common for both modules. How do I go about this the right way?

**Comment by claudio-silva** [comment]
Hi @sokolandia 
Have you read [this thread](https://github.com/claudio-silva/grunt-angular-builder/issues/8) ?
Just read it till the bottom, perhaps you can get some ideas from there... .

Also, take a look at [this](https://github.com/claudio-silva/grunt-angular-builder/wiki/Configuring-tasks#overridedependencies-middleware).
See if it helps.

**Comment by claudio-silva** [comment]
As I have not heard from you for a very long time, I'm closing this issue.
