### ISSUE TITLE
Files viewed but ignored

### ISSUE THREAD

**Issue by DanieleSassoli** [claudio-silva/grunt-angular-builder#20]
Hi,
I'm a bit new to grunt and it's the first time I'm trying to modularize an angularjs app on my own. 
I have my files structure which looks like this: 
* app
    *  scripts
      * controllers
          * controller1.js
      * services
          * service1.js
    * app.js

and this is my grunt configurations 

     'angular-builder': {
        options: {
            mainModule: 'SocialPhotoApp',
            externalModules: 'ezfb',
            releaseBuild: {
               renameModuleRefs: true
            }
        },
         app: {
            src: 'app/scripts/**/*.js',
            dest: 'build/saxSocialPhotoApp.js'
        }
    },
and my app.js looks like this

    var SocialPhotoApp = angular
        .module('SocialPhotoApp', ['custom-dependency']);

and my controller1.js looks like this: 

     SocialPhotoApp.controller('FacebookCtrl',['$scope',
         function($scope){
     }]);
I want my controller to be included in the build but for some reason grunt-angular-build ignores controller1.js, I tried adding //#require (path/to/file) in the js script, but nothing changed, I tryed adding the require:'path/to/file' in the grunt task configuration, but again nothing changed, someone has some ideas?
thanks.

**Comment by DanieleSassoli** [comment]
I just find a solution, as it's stated in the documentation  

>You may not assign your module to a global variable (nor is it a good practice).
>Also, you are not able to share such a variable between files related to the same module.

So changing

    SocialPhotoApp.controller('FacebookCtrl',['$scope',
         function($scope){
     }]);
to  

    angular.module('SocialPhotoApp').controller('FacebookCtrl',['$scope',
         function($scope){
     }]);

Solved my problem.

**Comment by claudio-silva** [comment]
Hi @DanieleSassoli 
I'm glad you've managed to solve your issue.
And I hope Angular Builder will be useful to you.
Regards
