### ISSUE TITLE
SourceMaps support

### ISSUE THREAD

**Issue by nikgraf** [claudio-silva/grunt-angular-builder#21]
I was looking for a way to support sourcemaps, but couldn't find anything in the docs nor code. Is it possible? Are there any recommendations especially in combination with uglify?

**Comment by claudio-silva** [comment]
Hi @nikgraf,
There are two scenarios for using Angular Builder:
##### Building for development/debugging
You can run the Builder in "debug mode", where your original source code files will be loaded directly, and in the correct dependency order.
If you're compiling some other language to JavaScript, make sure to include sourcemap generation on the compiling step, before Angular Builder is invoked. Also make sure your compiling step places source maps next to the compiled source files (i.e. the generated JavaScript files that should be placed on some temporary folder for being processed next by Angular Builder).
##### Building for production/release
When running on production mode, all your source code files will be merged, and it's currently not possible to generate a source map that maps to the original files (but you can still generate one that maps to the merged file).
As for Uglify, you should use it only for "release" builds (for production), so there should be no need for sourcemaps (as they're meant for debugging).

**Comment by nikgraf** [comment]
@claudio-silva When using error tracking software like Rollbar it's really hard debug what's going on without sourcemaps and therefor they are really handy for production releases. Is there any reason why you would not use sourcemaps for production releases?

https://rollbar.com/docs/source-maps/

**Comment by claudio-silva** [comment]
I see. 
Are you transpiling to javascript, or do you just need to map from the built files to the original JavaScript files?

**Comment by nikgraf** [comment]
In case of en error it would great if it shows where it originated from in the original file. With grunt uglify there is a way to leverage existing source files. https://github.com/gruntjs/grunt-contrib-uglify#sourcemapincludesources

**Comment by nikgraf** [comment]
thx for your fast response & looking into this: https://github.com/claudio-silva/grunt-angular-builder/issues/21

**Comment by claudio-silva** [comment]
You're welcome.
But, unfortunately, I'm not sure I'll be able to help you.
If you really need source maps for production code, then currently Angular Builder only allows those sourcemaps to map to the output build files. You may have a single output file, or multiple output files (ex. for libraries), but every build file is comprised of multiple merged source files, possibly optimized and transformed in some ways. So, it's not trivial to map to the original source files.
One could, possibly, build a middleware for Angular Builder that would  generate mapping information and embed it on the generated output, but it would still not be possible to map code generated and/or transformed by the build process (because it doesn't exist on the original source code).

**Comment by edwinm** [comment]
@claudio-silva, other tools like UglifyJS can take the source maps from a previous step, do the processing and writes out an updated source map still pointing to the original files.

See the UglifyJS command line options:
https://github.com/mishoo/UglifyJS2

It uses the source-map library from Mozilla, maybe you can use that? It supports input source maps from a previous step. (I couldn't find which lib you were using for source maps).
https://github.com/mozilla/source-map

**Comment by claudio-silva** [comment]
Thank you @edwinm for your suggestion, but I still think it won't work on this particular case. Transformations applied on the release build process can make the generated code diverge substantially from the original one, so I don't believe it's possible to map from one to the other, or if it is, it is technically quite difficult to implement and I'm currently not willing to undertake that task, as there is little benefit. Angular 1 is slowly being phased out, and, alas, soon this project will be obsolete.
