### ISSUE TITLE
window.angular

### ISSUE THREAD

**Issue by SamanthaAdrichem** [claudio-silva/grunt-angular-builder#24]
The basic angular usage

```
(function(angular) {
angular.module('x', []);
})(window.angular);

```
is not properly removed / replaced.

**Comment by claudio-silva** [comment]
Thanks for reporting this.
Are you writing this kind of code in your app, or have you found it on third party libraries that you're including on your build?

**Comment by SamanthaAdrichem** [comment]
Hey Claudio, sorry for the late response, was waiting for a response from my dev why we should use this kind of statement.

We use it in our code, it is suggested because code editors will otherwise give validation errors for not using it, as being a bad practice.

So basically we enclose everything with 

```
(function( angular ) {
})( window.angular );
```

The resulted optimised module definition makes code harder to read, due to the model being defined at the bottom, so thats a type of statement we do not prefer in our development code.

**Comment by claudio-silva** [comment]
Thank you for your response.
Is this currently a problem for you?
Or have you manged to find a workaround?
Also, if you feel you can patch the code to allow the `window.angular` construct, I'm willing to accept a pull request.
I'm sorry to not volunteer for doing it myself, as I'm very busy right now and I just don't have the time for it.

**Comment by claudio-silva** [comment]
Due to a prolonged lack of response, I'm going to close this. Feel free to reopen it if you feel the issue was not properly addressed.
