### ISSUE TITLE
including templates in build

### ISSUE THREAD

**Issue by aleclofabbro** [claudio-silva/grunt-angular-builder#25]
Hello Claudio,
after a long time i'm here again ;)
this time i managed to include `angular-builder` as a build tool for a very large project..
I'm setting up the dev environment, and i bumbed into a scenario that i can't figure out ..
the wiki says that each assetpath  (be it a template, a css, or whatever) should:
> The specified path should be a relative path (not starting with /); it will be relative to the file containing the directive.

take in consideration templates (but it would be the same for other assets): 
a directive in  subfolder `path/of/moduleone/` declares:
`//# template ("main.html")` and
`templateUrl:'main.html'`
How to handle the asset resolution later?

**option 1:**
a subsequent (for instance `ngTemplates`) task should manage `requiredTemplates` and register the `path/of/moduleone/main.html` template stripping the path leaving `main.html` alone to let the directive access it in runtime..
It seems to me that this easily leads to conflicts, as other  directives in other subfolders may use a template with same name.
This could be workarounded naming the template wwith long names, maybe reflecting the directive or module folder structure as `path-of-moduleone-main.html` but it doesn't look nice..

**option 2:**
no subtask manages the `requiredTemplates` and templates would be accessed in runtime, the directive will not fetch it because it has no path to it

**option 3:**
the `angular-builder` annotation for template is relative but the `templateUrl` annotation is absolute, this
should work with some custom mappping of  `requiredTemplates` array.. but it looks a bit counterintuitive.

however the relative path constraint would make any asset-sharing between modules very awkward  

i wonder if i'm missing the point about this feature.

thank you Claudio. 

[EDIT]
i saw the path is pushed in the array in https://github.com/claudio-silva/grunt-angular-builder/blob/master/tasks/middleware/exportRequiredTemplates.js#L114  

a solution in my opinion could be to (optionally) use non-relative paths and declare them in the same way both in `templateUrl` and in `//# template `,  
the developer should know how to handle that *pseudo-absolute* url..
`paths.push (path.normalize (path.dirname (filePath) + '/' + url));`  ->
`paths.push(path.normalize(url));`

**Comment by claudio-silva** [comment]
Hello Alessandro,
I'm glad Angular Builder is still useful for you.
As a side note, I'm curious: with Angular 2 coming, is your company still betting on Angular 1 for developing new apps?
I haven't touched this code in a long time, given that Angular 2 makes it obsolete; we're using it on our existing apps but we're not developing anything new with it.

As for your problem:
I don't see any problem with directives defining their templates as:
```
templateUrl: 'path/to/module/directive/templates/main.html'
```
This way, there's no chance of conflicts occurring. It's just a matter of defining conventions for your app, and sticking to them. In fact, that's how we do it on our apps.
As for the `//#template` reference being relative while `templateUrl` is pseudo-absolute, I didn't think it would be a big deal, as it would be easier to reference relative paths; but I didn't anticipate the possibility of assets being shared between modules. We didn't use this feature for that purpose.
If you feel it's important that `//#template` references become absolute, you can submit a pull request; but I worry that someone else may be using that feature and the change may brake things for them.

**Comment by aleclofabbro** [comment]
Hi Claudio,
We evaluated Angular2 but it's in beta (not big issue) but more important it's based on WebComponents which are still unsupported in all browsers but Chrome, and the future support is uncertain (at least concerning the "when")..  
we don't want to rely on the polyfill, that has big performance hit and is not 100% reliable..
At the time we can't defer the application startup, so  .. Angular1.. 
It seems ng1.x,  and ecosystem, is still fit and good health, and in development.. it doesn't look toward sunset..
What's  your opinion about it? 
Another thing... maybe i  didnt grok it well, but it seems to me that WebComponents, in general, are the best  choice for widely-shareable mix and match components, but they don't fit very well for business applications.. 
e.g. a feature like style shadowing is great for the first scenario, but it's a drag for an enterpirse application, whose modules/components  normally share many assets, css, js...
..
said that,
yes option 3 is not that bad,  it's just indeed i didn't like to write  2 differernt urls: 1 relative and 1 absolute in a directive definition..
but i may opt for forking  the repo and modify those lines, even more so if, as you let me know, this project is considered obsolete :(

Thanks !

**Comment by claudio-silva** [comment]
Hi,
I believe you are not required to use web components technology on your Angular 2 apps, it's a opt-in feature.
[This article](http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html) explains it best.
As for if web components are a good choice, currently they are not, but we are seeing frameworks (llike Angular 2) taking some of the technologies underlying web components (like shadow dom, templates and styles encapsulation) and using them in innovative ways. And that is good. Web components may eventually fail to take traction, but the underlying technologies might evolve into something completely different and power other frameworks and other kinds of solutions.

Did you solve your problem with the relative URLs?

**Comment by claudio-silva** [comment]
Due to a prolonged lack of response, I'm going to close this. Feel free to reopen it if you feel the issue was not properly addressed.
